site_name: apicactl - Command-line tool for the Apica Ascent Platform
site_url: https://logiqctl.logiq.ai/

theme:
  name: material
  palette:
    - scheme: slate
  logo: media/apica-white.svg
  favicon: media/apica.svg
  font:
    text: Nunito
    code: Source Code Pro
  features:
    - navigation.instant
    - navigation.top 
  static_templates:
    - 404.html
  include_search_page: false
  search_index_only: true

markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search:
      separator: '[\s\-\.]+'

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ApicaSystem
      name: Fork Apicactl on GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/apicaio
      name: Follow Apica on Twitter
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UC3tnc4KVJh3nOI-4d8HKl-Q
      name: Watch Apica videos on YouTube
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/apica-ab
      name: Join Apica on LinkedIn

extra_css:
  - extra/style.css


nav:
  - Versions:
    - 2.0.1: https://logiqctl.logiq.ai/2.0.1/
    - 2.0.0: https://logiqctl.logiq.ai/2.0.0/
  - apicactl: index.md
  - config:
    - apicactl config: config/apicactl_config.md
    - apicactl config init: config/apicactl_config_init.md
    - apicactl config set-cluster: config/apicactl_config_set-cluster.md
    - apicactl config set-context: config/apicactl_config_set-context.md
    - apicactl config set-context interactive: config/apicactl_config_set-context_interactive.md
    - apicactl config set-credential: config/apicactl_config_set-credential.md
    - apicactl config set-token: config/apicactl_config_set-token.md
    - apicactl config view: config/apicactl_config_view.md
  - create:
    - apicactl create: create/apicactl_create.md
    - apicactl create dashboard: create/apicactl_create_dashboard.md
    - apicactl create eventrules: create/apicactl_create_eventrules.md
  - get:
    - apicactl get:  get/apicactl_get.md
    - apicactl get applications: get/apicactl_get_applications.md
    - apicactl get applications all: get/apicactl_get_applications_all.md
    - apicactl get dashboard: get/apicactl_get_dashboard.md
    - apicactl get dashboard all: get/apicactl_get_dashboard_all.md
    - apicactl get datasource: get/apicactl_get_datasource.md
    - apicactl get datasource all: get/apicactl_get_datasource_all.md
    - apicactl get eventrules: get/apicactl_get_eventrules.md
    - apicactl get eventrules all: get/apicactl_get_eventrules_all.md
    - apicactl get eventrules groups: get/apicactl_get_eventrules_groups.md
    - apicactl get events: get/apicactl_get_events.md
    - apicactl get httpingestkey: get/apicactl_get_httpingestkey.md
    - apicactl get namespaces: get/apicactl_get_namespaces.md
    - apicactl get processes: get/apicactl_get_processes.md
    - apicactl get query: get/apicactl_get_query.md
    - apicactl get query all: get/apicactl_get_query_all.md
    - apicactl get query result: get/apicactl_get_query_result.md
  - license:
    - apicactl license: license/apicactl_license.md
    - apicactl license get: license/apicactl_license_get.md
    - apicactl license set: license/apicactl_license_set.md
  - logs: 
    - apicactl logs: logs/apicactl_logs.md
    - apicactl logs interactive: logs/apicactl_logs_interactive.md
    - apicactl logs search: logs/apicactl_logs_search.md
  - tail:
    - apicactl tail: tail/apicactl_tail.md
  - Guides:
    - Pattern-signature generation: guides/pattern-signature-generation.md
    - Using LOGIQHub dashboards: guides/using-apicahub-dashboards.md


