// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.21.5
// source: api/proto/realtimeLogStream.proto

package realtimeLogStream

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Subscription struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Applications []string `protobuf:"bytes,1,rep,name=applications,proto3" json:"applications,omitempty"`
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_realtimeLogStream_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_realtimeLogStream_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_api_proto_realtimeLogStream_proto_rawDescGZIP(), []int{0}
}

func (x *Subscription) GetApplications() []string {
	if x != nil {
		return x.Applications
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Log string `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_realtimeLogStream_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_realtimeLogStream_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_api_proto_realtimeLogStream_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

var File_api_proto_realtimeLogStream_proto protoreflect.FileDescriptor

var file_api_proto_realtimeLogStream_proto_rawDesc = []byte{
	0x0a, 0x21, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x61, 0x6c,
	0x74, 0x69, 0x6d, 0x65, 0x4c, 0x6f, 0x67, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x11, 0x72, 0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x4c, 0x6f, 0x67,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x22, 0x32, 0x0a, 0x0c, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x70,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x1c, 0x0a, 0x08, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x6f, 0x67, 0x32, 0x63, 0x0a, 0x12, 0x4c, 0x6f, 0x67, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4d,
	0x0a, 0x09, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4c, 0x6f, 0x67, 0x12, 0x1f, 0x2e, 0x72, 0x65,
	0x61, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x4c, 0x6f, 0x67, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e,
	0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x1b, 0x2e, 0x72,
	0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x4c, 0x6f, 0x67, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x48, 0x5a,
	0x46, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x6f, 0x67, 0x69,
	0x71, 0x61, 0x69, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x71, 0x63, 0x74, 0x6c, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x4c, 0x6f, 0x67, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x3b, 0x72, 0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x4c, 0x6f,
	0x67, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_realtimeLogStream_proto_rawDescOnce sync.Once
	file_api_proto_realtimeLogStream_proto_rawDescData = file_api_proto_realtimeLogStream_proto_rawDesc
)

func file_api_proto_realtimeLogStream_proto_rawDescGZIP() []byte {
	file_api_proto_realtimeLogStream_proto_rawDescOnce.Do(func() {
		file_api_proto_realtimeLogStream_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_realtimeLogStream_proto_rawDescData)
	})
	return file_api_proto_realtimeLogStream_proto_rawDescData
}

var file_api_proto_realtimeLogStream_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_realtimeLogStream_proto_goTypes = []interface{}{
	(*Subscription)(nil), // 0: realtimeLogStream.Subscription
	(*Response)(nil),     // 1: realtimeLogStream.Response
}
var file_api_proto_realtimeLogStream_proto_depIdxs = []int32{
	0, // 0: realtimeLogStream.LogStreamerService.StreamLog:input_type -> realtimeLogStream.Subscription
	1, // 1: realtimeLogStream.LogStreamerService.StreamLog:output_type -> realtimeLogStream.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_realtimeLogStream_proto_init() }
func file_api_proto_realtimeLogStream_proto_init() {
	if File_api_proto_realtimeLogStream_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_realtimeLogStream_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Subscription); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_realtimeLogStream_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_realtimeLogStream_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_realtimeLogStream_proto_goTypes,
		DependencyIndexes: file_api_proto_realtimeLogStream_proto_depIdxs,
		MessageInfos:      file_api_proto_realtimeLogStream_proto_msgTypes,
	}.Build()
	File_api_proto_realtimeLogStream_proto = out.File
	file_api_proto_realtimeLogStream_proto_rawDesc = nil
	file_api_proto_realtimeLogStream_proto_goTypes = nil
	file_api_proto_realtimeLogStream_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// LogStreamerServiceClient is the client API for LogStreamerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LogStreamerServiceClient interface {
	StreamLog(ctx context.Context, in *Subscription, opts ...grpc.CallOption) (LogStreamerService_StreamLogClient, error)
}

type logStreamerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLogStreamerServiceClient(cc grpc.ClientConnInterface) LogStreamerServiceClient {
	return &logStreamerServiceClient{cc}
}

func (c *logStreamerServiceClient) StreamLog(ctx context.Context, in *Subscription, opts ...grpc.CallOption) (LogStreamerService_StreamLogClient, error) {
	stream, err := c.cc.NewStream(ctx, &_LogStreamerService_serviceDesc.Streams[0], "/realtimeLogStream.LogStreamerService/StreamLog", opts...)
	if err != nil {
		return nil, err
	}
	x := &logStreamerServiceStreamLogClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LogStreamerService_StreamLogClient interface {
	Recv() (*Response, error)
	grpc.ClientStream
}

type logStreamerServiceStreamLogClient struct {
	grpc.ClientStream
}

func (x *logStreamerServiceStreamLogClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LogStreamerServiceServer is the server API for LogStreamerService service.
type LogStreamerServiceServer interface {
	StreamLog(*Subscription, LogStreamerService_StreamLogServer) error
}

// UnimplementedLogStreamerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedLogStreamerServiceServer struct {
}

func (*UnimplementedLogStreamerServiceServer) StreamLog(*Subscription, LogStreamerService_StreamLogServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamLog not implemented")
}

func RegisterLogStreamerServiceServer(s *grpc.Server, srv LogStreamerServiceServer) {
	s.RegisterService(&_LogStreamerService_serviceDesc, srv)
}

func _LogStreamerService_StreamLog_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Subscription)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LogStreamerServiceServer).StreamLog(m, &logStreamerServiceStreamLogServer{stream})
}

type LogStreamerService_StreamLogServer interface {
	Send(*Response) error
	grpc.ServerStream
}

type logStreamerServiceStreamLogServer struct {
	grpc.ServerStream
}

func (x *logStreamerServiceStreamLogServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

var _LogStreamerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "realtimeLogStream.LogStreamerService",
	HandlerType: (*LogStreamerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLog",
			Handler:       _LogStreamerService_StreamLog_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/realtimeLogStream.proto",
}
