name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        path: /home/runner/go/src/github.com/${{ github.repository }}

    - name: Install protobuf
      run: sudo snap install protobuf --classic      
      
    - name: Generate protobuf code
      run:  GOPATH=/home/runner/go ./generate_grpc.sh  
      working-directory: /home/runner/go/src/github.com/${{ github.repository }}
      
    - name: Build
      run: GOPATH=/home/runner/go go build -v .
      working-directory: /home/runner/go/src/github.com/${{ github.repository }}
