name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
        path: ./src/github.com/${{ github.repository }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install protobuf
      run: sudo snap install protobuf --classic
            
    - name: Generate protobuf code
      run: ./generate_grpc.sh
      
    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v .
